### ISSUE TITLE
Wallet not connecting

### ISSUE THREAD

**Issue by MikeBlueberry** [pooltogether/pooltogether-pods-interface#10]
pods.pooltogether.com doesn't connect to wallets. It opens the popup with the wallets but doesn't proceed.

**Browser**: Brave 1.20.110 Chromium: 88.0.4324.192 version 64 bits
**Wallet**: MetaMask

Thank you.

**Comment by MikeBlueberry** [comment]
My fault: I was on the Matic network. When I switched to Ethereum's, it worked.

**Comment by kamescg** [comment]
@MikeBlueberry Glad it was resolved.

This is a signal we need to improve the network detection and messaging.
